// <auto-generated />
using System;
using GamothequeWPF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GamothequeWPF.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("GamothequeWPF.Model.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("DigitalSupport");

                    b.Property<bool>("Done");

                    b.Property<TimeSpan>("ExpectedDuration");

                    b.Property<int>("Mark");

                    b.Property<int>("MinimumAge");

                    b.Property<string>("Name");

                    b.Property<bool>("PhysicalSupport");

                    b.Property<string>("Picture");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Review");

                    b.Property<string>("Synopsis");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("GamothequeWPF.Model.GameTextLanguage", b =>
                {
                    b.Property<int>("IdGame");

                    b.Property<string>("NameLanguage");

                    b.HasKey("IdGame", "NameLanguage");

                    b.HasIndex("NameLanguage");

                    b.ToTable("GameTextLanguage");
                });

            modelBuilder.Entity("GamothequeWPF.Model.GameType", b =>
                {
                    b.Property<int>("IdGame");

                    b.Property<int>("IdType");

                    b.HasKey("IdGame", "IdType");

                    b.HasIndex("IdType");

                    b.ToTable("GameType");
                });

            modelBuilder.Entity("GamothequeWPF.Model.GameVoiceLanguage", b =>
                {
                    b.Property<int>("IdGame");

                    b.Property<string>("NameLanguage");

                    b.HasKey("IdGame", "NameLanguage");

                    b.HasIndex("NameLanguage");

                    b.ToTable("GameVoiceLanguage");
                });

            modelBuilder.Entity("GamothequeWPF.Model.Language", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Name");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("GamothequeWPF.Model.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Name");

                    b.HasKey("Id");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("GamothequeWPF.Model.GameTextLanguage", b =>
                {
                    b.HasOne("GamothequeWPF.Model.Game", "Game")
                        .WithMany()
                        .HasForeignKey("IdGame")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GamothequeWPF.Model.Language", "Language")
                        .WithMany()
                        .HasForeignKey("NameLanguage")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GamothequeWPF.Model.GameType", b =>
                {
                    b.HasOne("GamothequeWPF.Model.Game", "Game")
                        .WithMany()
                        .HasForeignKey("IdGame")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GamothequeWPF.Model.Type", "Type")
                        .WithMany()
                        .HasForeignKey("IdType")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GamothequeWPF.Model.GameVoiceLanguage", b =>
                {
                    b.HasOne("GamothequeWPF.Model.Game", "Game")
                        .WithMany()
                        .HasForeignKey("IdGame")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GamothequeWPF.Model.Language", "Language")
                        .WithMany()
                        .HasForeignKey("NameLanguage")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
